### ISSUE TITLE
Emails not being deleted

### ISSUE THREAD

**Issue by hkyq** [JensAstrup/pyOutlook#10]
Hey, so I've got this code:
```

            elif "[Auth2]" in email.subject:
                if email.subject.split()[2] == str(pswd):
                    username = email.subject.split()[1]
                    email.move_to_deleted()
                    authenticateUser(username)
```

But my emails aren't getting deleted, they remain in my inbox and the command runs without an error.

**Comment by hkyq** [comment]
Wow, that was fast. Also, might as well mention that when I attempted to move to a folder specified by an ID, I got a Folder is unknown error.

**Comment by JensAstrup** [comment]
I just tested this out and have no issues deleting, so my best guess is this is an access token issue. Are you sure you have the `mail.readwrite` scope? That being said, it should be raising an error - looking into that bit...

**Comment by hkyq** [comment]
This probably is an access token issue. And I'm not sure if I have `mail.readwrite`, could you maybe link me what it is?

**Comment by JensAstrup** [comment]
I was thinking to myself the other day that it may be beneficial to add more info about retrieving access tokens, can be a bit hard to find. https://docs.microsoft.com/en-us/outlook/rest/get-started is what you want, an example of the URL I have is:

`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=https://outlook.office.com/Mail.Send%20offline_access%20https://outlook.office.com/mailboxsettings.readwrite`

**Comment by hkyq** [comment]
Thanks, I will do the folder issue tomorrow. 
I'm kind of confused though, in the url it says I need to have a Developer Account or Student Account - is that why my access token isn't showing on my app's page?

**Comment by hkyq** [comment]
I'm kind of confused to as exactly what this is doing. I made the url with the readwrite scopes, and then linked it to my main outlook account. What does the app have to do with my personal access key?

**Comment by JensAstrup** [comment]
Want to shoot me an email? jensaiden (at) gmail

**Comment by hkyq** [comment]
Sure. I'm the protonmail.
