### ISSUE TITLE
Where to get a "static" api key?

### ISSUE THREAD

**Issue by hkyq** [JensAstrup/pyOutlook#11]
Hello, so currently I'm getting my api key from [here](https://oauthplay.azurewebsites.net), but it seems that it resets every like 40 minutes. (Yes, I've linked my Outlook account)
Where do you guys get your key?

**Comment by JensAstrup** [comment]
Don't believe there is one - but if you find a way, let me know! I just have a celery task running which refreshes the token - for a while I used Google Apps Scripts (free and you can run scheduled tasks ;) ). I keep the token stored in Firebase and just have everything pull the token from there.

**Comment by hkyq** [comment]
I was looking into Google Apps Scripts. Could you explain how you refresh the token? Sorry, I'm still a noob ;)

**Comment by JensAstrup** [comment]
Make a post request to https://login.microsoftonline.com/common/oauth2/v2.0/token with the payload:

```
{
refresh_token: token_from_initial_request,
client_id: your_client_id,
client_secret: your_client_secret,
grant_type: refresh_token,
scope: same_scope_you_initially_requested
}

```
you should get the following back:

```
{
access_token: 123,
refresh_token: 321
}
```

**Comment by hkyq** [comment]
Thanks. Will do this later today.
