### ISSUE TITLE
How to get to get access token for demon app.

### ISSUE THREAD

**Issue by the-spectator** [JensAstrup/pyOutlook#12]
Hi I want to create a demon app which has should not access the browser and till now all the methods I have explored are using web browser for getting access code. Any hint or guidance is appreciated.

**Comment by JensAstrup** [comment]
Apologies for the late reply - you'll need to go through the browser to get access tokens, and make HTTP requests to refresh the token periodically. I'm not aware of any way around that since pyOutlook uses the REST API: https://msdn.microsoft.com/en-us/office/office365/api/mail-rest-operations
