### ISSUE TITLE
are there plans for accessing Outlook calendar?

### ISSUE THREAD

**Issue by nnako** [JensAstrup/pyOutlook#15]
Hi,

additional to handling Outlook's emails via python, it would be handy to be able to manage TASKS and CALENDAR entries using a Python interface.

Are there plans for including these kind of features into pyOutlook's code base?

Thanks.

**Comment by JensAstrup** [comment]
Sorry the for delay here,

There's a long term goal to add support for contacts, but I haven't taken a look at the calendar features yet.
