### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by tarrenj** [JensAstrup/pyOutlook#6]
It would be very helpful if this included support for sending encrypted emails.

**Comment by JensAstrup** [comment]
Everything is going through the [Outlook REST API](https://msdn.microsoft.com/office/office365/APi/mail-rest-operations#create-and-send-messages) which uses HTTPS, but beyond that I'm not sure what can be improved. If you have any ideas, definitely share and I'll try to implement - pull requests also accepted :)
