### ISSUE TITLE
Issues with python syntax in main.py on line 31, 79, 88, 157

### ISSUE THREAD

**Issue by philiphoyos** [JensAstrup/pyOutlook#9]
It seems that there is something wrong with the syntax in the following lines.

**031**: `def get_message(self, message_id) -> Message:`
**079**: `def new_email(self, body='', subject='', to: List[Contact] = list):`
**088**: `def send_email(self, body=None, subject=None, to: List[Contact] = list, cc=None, bcc=None, send_as=None, attachments=None):`
**157**: `def _get_messages_from_folder_name(self, folder_name: str):`

**Comment by JensAstrup** [comment]
Are you on Python 3?

**Comment by philiphoyos** [comment]
Ahh. Im sorry about that. Just remove my issue :)

**Comment by JensAstrup** [comment]
You're not the first to bring up something related to Python 2, I opened an issue in the GitLab repo about supporting Python 2 in the next release :)

**Comment by JensAstrup** [comment]
Python 2 support added - https://pypi.org/project/pyOutlook/4.1.0.dev1/

**Comment by philiphoyos** [comment]
Ah  cool! Thanks!
